---
title: "testing-checking ohun functions aug-2021"
author: "Marcelo Araya-Salas"
date: "aug 21, 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

# uninstall  
```{r reinstall from github, eval=F}

remove.packages("suwo")
# 
# #restart R
.rs.restartR()

```

# install/load packages
```{r packages, eval=T}

# devtools::install()

remotes::install_github("ropensci-review-tools/pkgcheck")

pkgs <- c("remotes", "curl", "RCurl", "jsonlite", "crayon", "devtools", "leaflet", "maps", "pkgcheck", "pkgstats", "testthat", "styler", "cli")

# install/ load packages
out <- lapply(pkgs, function(y) {
  
  # get pakage name
  pkg <- strsplit(y, "/")[[1]]
  pkg <- pkg[length(pkg)]
  
  # check if installed, if not then install 
  if (!pkg %in% installed.packages()[,"Package"])  {

      if (grepl("/", y))  remotes::install_github(y, force = TRUE) else
    install.packages(y) 
    }

  # load package
  a <- try(require(pkg, character.only = T), silent = T)

  if (!a) remove.packages(pkg)
  })



rm(list = ls())

# install ctags
# first run in terminal: sudo apt install lsb-core

# then run this with sudo privilege
# ctags_install(bin_dir = NULL, sudo = TRUE)


# load_all()

```

# functions
```{r functions, eval = T}

# run internals
run_ohun_int <- function(){ 
out <- lapply(list.files(pattern = "ohun_int", path = "./R", full.names = T), source)}

# open working directory
open.wd <- function() system(paste("nautilus", getwd()), show.output.on.console = F)

#open function in rstudio
open.fun <- function(fun) system(paste("rstudio", file.path("./R", paste0(fun, ".R"))))

# run default arguments in a warbleR function
run.def.args <- function(fun = NULL){

  #list functions in package
rfiles <- list.files(pattern = ".R", path = "./R", full.names = T)

# select target function file
funfile <- rfiles[gsub(".R", "", basename(rfiles)) == fun]

  x <- readLines(funfile, warn = F)
  st <- grep('@usage', x, fixed = T)
  en <- grep('@param', x, fixed = T)[1]
  x <- paste(x[st:(en-1)], collapse = " ")  
  x <- gsub("usage|\\@|\\#\\'", "", x)

  b <- gregexpr(pattern ='\\(|\\)',x)[1][[1]]
  x <- substr(x, start = b[1] + 1, stop = b[length(b)] - 1)
  spltx <- strsplit(x, "\\,")[[1]]

sl <- vector()
  y = 1
 
      while(y <= length(spltx))
        {
        w <- spltx[y]
        z <- 1
        if(grepl('\\(', spltx[y])) 
          {z  <- 0
          while(!grepl('\\)', w))
          {
              z <- z+ 1
              w <- paste(w, ",", spltx[y + z], collapse = "")
          }
        z <- z + 1
          }
        
       y = y + z
       sl[length(sl) + 1] <- w
            }

  sl <- sl[sl != "X"]
  return(sl)
  }

# run it like this: 
# for(i in run.def.args("dfts")) try(eval(parse(text = i)), silent = T)

# remove sound files and or image files
rm.sf <- function() unlink(list.files(path = tempdir(), pattern = "\\.wav$|\\.flac$|\\.mp3$|\\.wac$", ignore.case = T, full.names = TRUE))

rm.sf.img <- function(mp3 = TRUE) {if(mp3)
  unlink(list.files(path = tempdir(), pattern = "\\.wav$|\\.flac$|\\.mp3$|\\.wac$|\\.tiff$|\\.jpeg$|\\.png$", ignore.case = T, full.names = TRUE)) else
      unlink(list.files(path = tempdir(), pattern = "\\.wav$|\\.flac$|\\.wac$|\\.tiff$|\\.jpeg$|\\.png$", ignore.case = T, full.names = TRUE))}

rm.img <- function() unlink(list.files(path = tempdir(), pattern = "\\.tiff$|\\.jpeg$|\\.png$|\\.pdf$", ignore.case = T, full.names = TRUE))

#open latest image
last.img <- function() system(paste("eog", list.files(path = tempdir(), pattern = "\\.tiff$|\\.jpeg$", ignore.case = T, full.names = TRUE)[which.max(file.mtime(list.files(path = tempdir(), pattern = "\\.tiff$|\\.jpeg$", ignore.case = T, full.names = TRUE)))]
))

#open pdf
last.pdf <- function() system(paste("xdg-open", list.files(path = tempdir(), pattern = "\\.pdf$", ignore.case = T, full.names = TRUE)[which.max(file.mtime(list.files(path = tempdir(), pattern = "\\.pdf", ignore.case = T, full.names = TRUE)))]
))

#find text in functions
find.text <- function(pattern, fun.only = FALSE, path = "./R", ignore.case = TRUE, file.ext = "\\.R$|\\.Rmd$", recursive = TRUE)
  {
rfiles <- list.files(pattern = file.ext, path = path, full.names = T, all.files = T, ignore.case = ignore.case, recursive = recursive)
  
#check where a word is found in each function an return the name of function where it was found and the time
res <- NULL
w <- 1
for(f in rfiles){
  x <- readLines(f)
  y <- grep(pattern, x, fixed = T, value = T, ignore.case = ignore.case)
  if(length(y)>0 & !fun.only) {
    print(gsub(pattern = "\\.R", "", (basename(f)))) 
    for(i in y) print(i)
  }
  if(length(y)>0 & fun.only) res[w] <- gsub(pattern = "\\.R", "", (basename(f))) 
# options(nwarnings = 0)
  w = w + 1
}
if(fun.only)
{res <- res[!is.na(res)]
return(res)}
}


#replace text
repl.text <- function(pattern, repl, path = "./R", ignore.case = T, file.ext = "\\.R$|\\.Rmd$", recursive = TRUE){
  rfiles <- list.files(pattern =file.ext, path = path, full.names = T, all.files = T, ignore.case = ignore.case, recursive = recursive)

    for(f in rfiles){
  
    #find and replace
      x <- readLines(f)
      y <- gsub(pattern, repl, x, fixed = T, ignore.case = ignore.case)
      cat(y, file=f, sep="\n")
  
  #reread
      x <- readLines(f)
      w <- grep(repl, x, fixed = T, value = T, ignore.case = T)
      if(length(w)>0) {
          print(f) 
        for(i in w) print(i)
          }
    }
}

#find functions with specific arguments
find.arg <- function(arg1, arg2 = NULL){
  
  rfiles <- list.files(pattern = "\\.R$", path = "./R", full.names = T, all.files = T)
  
  funs <- gsub(pattern = "\\.R", "", (basename(rfiles)))
  funs <-grep("zzz|data|package", funs, invert = T, value = T)
  
l1 <- unlist(lapply(funs, function(x)
{  a <-  try(run.def.args(x), silent = T)
  if(any(grep(arg1, a))) return(x)
}      ))

if(!is.null(arg2))
{l2 <- unlist(lapply(funs, function(x)
{  a <-  try(run.def.args(x), silent = T)
  if(any(grep(arg2, a))) return(x)
}      ))

res <- intersect(l1, l2)

} else res <- l1

return(res)

}

# run default arguments
run.def.args2 <-function(FUN)
{
  fm <- formals(FUN)

  
fm <- fm[sapply(fm, length) > 0 | sapply(fm, is.null)]

fm <- lapply(1:length(fm), function(x) paste(names(fm)[x], "=", fm[x]))

for(i in fm) try(eval(parse(text = i)), silent = T)

}


#find functions with specific arguments and text
find.arg.text <- function(arg1, arg2 = NULL, pattern) {
  
  f1 <- find.text(pattern = pattern, fun.only = T)
f2 <- find.arg(arg1 = arg1, arg2 = arg2)

return(intersect(f1, f2))
}
  
#bid data set
big.seltab <- function(X, nrow = 100){
Y <- X[rep(1:nrow(X), ceiling(nrow/nrow(X)))[1:nrow],]
  Y$selec <- 1:nrow(Y)
if(is_selection_table(Y) | is_extended_selection_table(Y))
  
  attr(Y, "check.results") <- attr(X, "check.results")[rep(1:nrow(attr(X, "check.results")), ceiling(nrow/nrow(attr(X, "check.results"))))[1:nrow],]
  
  attr(Y, "check.results")$selec <- 1:nrow(Y)
  return(Y)
}

#write all wav files in lbh_selec_table
write.sound.files <- function(path = tempdir(), extensible = T, other.formats = FALSE, simulated = FALSE){
  # setwd(path)
data(lbh1, package = "ohun")
data(lbh2, package = "ohun")
tuneR::writeWave(lbh1, file.path(tempdir(),  "lbh1.wav"), extensible = extensible) #save sound files 
tuneR::writeWave(lbh2, file.path(tempdir(),  "lbh2.wav"), extensible = extensible) #save sound files 

if (simulated){
  
  # Creating vector for duration
durs <- rep(c(0.3, 1), 5)

# Creating simulated song
set.seed(12)

simulated_1 <- warbleR::simulate_songs(n = 10, durs = durs, freqs = 5, sig2 = 0.01, gaps = 0.5, harms = 1, bgn = 0.1, path = tempdir(), file.name = "simulated_1", selec.table = TRUE, shape = "cos", fin = 0.3, fout = 0.35, samp.rate = 18)

sim_2 <- sim_songs(n = 10, durs = durs, freqs = 5, sig2 = 0.01, gaps = 0.5, harms = 1, bgn = 0.1, path = tempdir(), file.name = "simulated_2", selec.table = TRUE, shape = "cos", fin = 0.3, fout = 0.35, samp.rate = 18, am.amps = c(1, 2, 3, 2, 0.1, 2, 3, 3, 2, 1))

sel_tab2 <- sel_tab1 <- simulated_1$selec.table
sel_tab2$sound.files <- gsub("_1", "_2", sel_tab2$sound.files)

sel_tab <- rbind(sel_tab1, sel_tab2)
return(sel_tab)
}
# if (other.formats){
#   file.copy(from = system.file("extdata", "recording_20170716_230503.wac", package = "bioacoustics"), to = file.path(tempdir(), "recording_20170716_230503.wac"))
# 
# file.copy(from = "../Phae.long4.mp3", to = file.path(tempdir(),  "Phae.long4.mp3"))
# 
#   file.copy(from = file.path(tempdir(), "Phae.long1.wav"), to = file.path(tempdir(), "Phae.long5.wav"))
# 
# wav2flac(file.path(tempdir(), "Phae.long5.wav"))
# 
# if (selection.table){
#   
#   lbh_selec_table$sound.files <- as.character(lbh_selec_table$sound.files)
# 
#   sub_tab <- lbh_selec_table[lbh_selec_table$sound.files %in% c("Phae.long1.wav", "Phae.long4.wav"), 1:7]
#   
#   sub_tab$sound.files[sub_tab$sound.files == "Phae.long1.wav"] <- "Phae.long5.flac"
#   
#     sub_tab$sound.files[sub_tab$sound.files == "Phae.long4.wav"] <- "Phae.long4.mp3"
# 
#     # fix times
#      sub_tab$start[sub_tab$sound.files == "Phae.long4.mp3"] <- c(0.2085945, 1.5950019, 2.3057996)
#      
#      sub_tab$end[sub_tab$sound.files == "Phae.long4.mp3"] <- c(0.3528653, 1.7287163, 2.4289576)
#     
#     
#     sub_tab <- rbind(sub_tab, data.frame(sound.files = "recording_20170716_230503.wac", channel = 1, selec = 1, start = 0.1, end = 0.3, bottom.freq = 2, top.freq = 10))
#   
#     sub_tab <- rbind(sub_tab, lbh_selec_table[, 1:7])
#     
#     sub_tab$format <-ifelse(grepl("flac$", sub_tab$sound.files), "flac", ifelse(grepl("mp3$", sub_tab$sound.files), "mp3", "wav"))
# 
#     
#     return(sub_tab)  
# } else return(NULL)


  # }
}

# run all warbleR fuctions
run.all <- function() invisible(lapply(list.files(pattern = "\\.R", path = "./R", full.names = T, all.files = T), function(x) source(x)))

# run.all()

list.selection.table <- function(lbh_selec_table, path = tempdir())
{
  crr.dr <- getwd()
    on.exit(setwd(crr.dr))
    
  if(!is.null(path)) setwd(path) 
  
  Xlist <- list()
Xlist$Xdf <- lbh_selec_table
Xlist$Xst <- selection_table(lbh_selec_table)
Xlist$Xest <- selection_table(lbh_selec_table, extended = T, confirm.extended = F)  

lbh_selec_table$song <- as.numeric(lbh_selec_table$sound.files)

Xlist$Xestbs <- selection_table(X = lbh_selec_table, extended = T, by.song = "song", confirm.extended = F)  

names(Xlist) <- c("DATA.FRAME", "SELECTION_TABLE", "EXTENDED_SELECTION_TABLE", "by.song.EXTENDED_SELECTION_TABLE")

return(Xlist)
}


bi_mats <- function(X, labels) {
  
  # create empty matrix to store memebership matrix
  mat <- matrix(nrow = ncol(X), ncol = ncol(X))
 
  # add labels to row and col names
  rownames(mat) <- colnames(mat) <- labels
  
  # add 0 if same lek and 1 if else 
  out <- lapply(1:(length(labels) - 1), function(i){
  sapply((i + 1):length(labels), function(j) 
    if (labels[i] == labels[j]) 0 else 1)  
    })

  # add to mat
  mat[lower.tri(mat)] <- unlist(out)

  # retunr as distance matrix
  return(as.dist(mat))
}

plot_detection <- function(reference, detection, lwd = 90, sep = 1, labels = detection$selec){

  if (!is.null(detection$detection.class)){
    labels <- ifelse(detection$detection.class == "true.positive", "\nTP", ifelse(detection$detection.class == "false.positive", "\nFP", ifelse(detection$detection.class == "false.negative", "\nFN", ifelse(detection$detection.class == "true.positive (split)", "\nTPs", ifelse(detection$detection.class == "true.positive (merged)", "\nTPm", ifelse(detection$detection.class == "negative (split)", "\nNs", ifelse(detection$detection.class == "negative (merged)", "\nNm", ifelse(detection$detection.class == "negative (split/merged)", "\nNsm", "\nTPsm"))))))))
    
    detection$labels <- paste0(detection$selec, labels)
    } else detection$labels <- detection$selec
  
  old_par <- par()
  old_par <- old_par[!names(old_par) %in%  c("cin", "cra", "csi", "cxy", "din", "page")]
  on.exit(par(old_par))
  par(mar = rep(0, 4))
  
  n_sound.files <- length(unique(c(reference$sound.files, detection$sound.files)))
  if (n_sound.files > 1)
    par(mfrow = c(n_sound.files, 1))


for (e in unique(c(detection$sound.files, reference$sound.files))){
  sub_detec <- detection[detection$sound.files == e, ]
  sub_ref <- reference[reference$sound.files == e, ]
  plot(x = range(c(sub_detec$start, sub_detec$end, sub_ref$start, sub_ref$end)), y = c(-1, 1), col = "white", pch = 21, yaxt = "n", ylab = "", xaxt = "n", xlab = "")
    
# plot references first
    if (nrow(sub_ref) > 0)
    for (i in 1:nrow(sub_ref)){
      segments(
        x0 = sub_ref$start[i],
        x1 = sub_ref$end[i],
        y0 = sep / -2,
        y1 = sep / -2,
        lwd = lwd,
        col = viridis::magma(10, alpha = 0.4)[3],
        lend = 1
      )
      text(x = (sub_ref$end[i] + sub_ref$start[i]) / 2, y = sep / -2, labels = i, col = "white")
    }

  # add detections  
    if (nrow(sub_detec) > 0)
    for (i in 1:nrow(sub_detec)){
      segments(
        x0 = sub_detec$start[i],
        x1 = sub_detec$end[i],
        y0 = sep / 2,
        y1 = sep / 2,
        lwd = lwd,
        col = viridis::magma(10, alpha = 0.4)[7],
        lend = 1
      )
        text(x = (sub_detec$end[i] + sub_detec$start[i]) / 2, y = sep / 2, labels = sub_detec$labels[i])
    }
  }
}

### simulate annotation tables
# cannot have duration shorter than 2
sim_annotation <- function(n = 10, n.sound.files = 1){
  
  sims_l <- lapply(1:n.sound.files, function(x){
    
  possible_start <- seq(0, 98, 2)
     
    sim_ref <- data.frame(sound.files = paste0(x, ".wav"), selec = 1:(n + 1), start = sort(c(sample(possible_start, n), 100)))
  
    
    sim_ref$end <- NA
    
    for(i in 1:(n))
          sim_ref$end[i] <- sim_ref$start[i] + round(runif(n = 1, min = 1, max = sim_ref$start[i + 1] - sim_ref$start[i] - 0.5))

    sim_ref <- sim_ref[-nrow(sim_ref), ]
    
      return(sim_ref)
    
  })

  sims <- do.call(rbind, sims_l)
  
  return(sims)
  }

```

# check
```{r check, eval = FALSE}

# styler::style_dir("./R")
# system("autoconf  ")

# usethis::use_rcpp()
# setwd("./warbleR/")
#delete NAMESPACE file

# Rcpp::compileAttributes()

#run document twice
devtools::document(".")
devtools::document(".")
# devtools::load_all()

# usethis::use_coverage()
# pkgcheck::use_github_action_pkgcheck()

#check with devtools

devtools::check(".", document = FALSE, run_dont_test = FALSE, vignettes = FALSE, manual = FALSE)

# devtools::run_examples( start = "rm_sil")

# devtools::build_manual()

# devtools::install()

devtools::test()

# check in R version 3.X.X

## run in terminal:
  # /opt/R/3.6.3/bin/R

# devtools::check("~/Dropbox/R_package_testing/warbleR/warbleR", document = TRUE, run_dont_test = TRUE, vignettes = FALSE, manual = TRUE)


```

# additional checks
```{r}
pkgcheck::pkgcheck(".")

cyclocomp::cyclocomp_package_dir(".")

pkgstats::pkgstats(".")

```

# check and build package
```{r check and build package, eval = FALSE}

# check spelling
schk <- devtools::spell_check(".")

schk

# check by function
schk$word[grep("optimize", schk$found)]

# check as in cran
system("R CMD check . --as-cran --resave-data=best")
system("R CMD check . --run-donttest")

# build tar.gz package file
system("R CMD build ./ --resave-data=best")

devtools::check(run_dont_test = TRUE)

unlink(list.files(pattern = "ohun\\.pdf", path = "."))

# only build manual 
#  sudo apt-get -f install texinfo
# sudo apt-get -f install texlive-fonts-extra

system("R CMD Rd2pdf .")

#built site
# pkgdown::build_site(lazy = TRUE, preview = TRUE, examples = FALSE)
# pkgdown::build_articles()
# 

# usethis::use_pkgdown()
# usethis::use_github_pages()


#sent to github
setwd(".")
system("git add .")
system('git commit -m  "suffix argument added to lspec()"')
system("git push origin master")


# installation of packages fo rOpenSci

# remotes::install_github ("ropensci-review-tools/pkgstats")

# usethis::use_github_action("pkgdown") 
# 
# #codecov
# usethis::use_coverage(format = c("codecov"))
# 
# covr::codecov(token = "94049bb4-baf6-4851-a830-405d9ae77a41")
# 
# usethis::use_github_action("test-coverage")

#generate codemeta.json (only run once)
# codemetar::write_codemeta()


## pckgcheck
x <- pkgcheck::pkgcheck(".")
summary(x)


```

# find and replace text
```{r, eval = FALSE}
# list.files

path <- "."

pattern <- "ffts"

find.text(pattern = pattern, fun.only = F, ignore.case = T, path = path, recursive = TRUE)

repl <- "freq_ts"

repl.text(pattern = pattern, repl = repl, path = path)

find.arg(arg1 = "dest.path")

# find NON-ASCII

out <- sapply(list.files("./man", full.names = TRUE), function(x) tools::showNonASCIIfile(file = x))


```

## troubleshoot suwo functions ####

```{r find_duplicates}

term <- "Turdus rufiventris"
xc_adf <- query_xenocanto(term = term)

wa_adf <- query_wikiaves(term = term, format = "sound")
 
gb_adf <- query_gbif(term = term, format = "sound")

in_adf <- query_inaturalist(term = term, format = "sound")
 
ml_adf <- query_macaulay(term = term, format = "sound", path = tempdir())

```



```{r query_observation, eval = FALSE}

FUN <- "query_observation"

#run function
source(file.path("./R", paste0(FUN,".R")))
# setwd(tempdir())

#open in rstudio
##open.fun(fun = FUN)

# remove objects but no functions
rm(list = setdiff(ls(), c(lsf.str(), "FUN")))

# to troubleshoot internally
for(i in run.def.args(FUN)) try(eval(parse(text = i)), silent = T)
rm(i)

source("~/Documentos/GitHub/suwo/R/internal_functions.R")

token <- "e9uJgF2mO0Vd81vd5N1kR1bZzuCWUA"

df1 <- query_observation(term = 'Glaucis dohrnii', format = "still image", token = token)

df1 <- query_observation(term = 'Turdus grayi', format = "still image", token = token)

df1 <- query_observation(term = 'Serinus serinus', format = "sound", token = token, cores = 2)

```

```{r query_xenocanto, eval = FALSE}

FUN <- "query_xenocanto"

#run function
source(file.path("./R", paste0(FUN,".R")))
# setwd(tempdir())

#open in rstudio
##open.fun(fun = FUN)

# remove objects but no functions
rm(list = setdiff(ls(), c(lsf.str(), "FUN")))

# to troubleshoot internally
for(i in run.def.args(FUN)) try(eval(parse(text = i)), silent = T)
rm(i)

source("./R/internal_functions.R")

options(verbose = TRUE)
df1 <- query_xenocanto(term = 'Glaucis dohrnii')

df1 <- query_xenocanto(term = 'Glaucis dohrnii')
df1 <- query_xenocanto(term = 'Turdus grayi')
df1 <- query_xenocanto(term = 'Serinus serinus')

df1 <- query_xenocanto(term = 'Chupacabras')
df1 <- query_xenocanto(term = 'Chupacabras')


```


```{r query_macaulay, eval = FALSE}

FUN <- "query_macaulay"

#run function
source(file.path("./R", paste0(FUN,".R")))
# setwd(tempdir())

#open in rstudio
##open.fun(fun = FUN)

# remove objects but no functions
rm(list = setdiff(ls(), c(lsf.str(), "FUN")))

# to troubleshoot internally
for(i in run.def.args(FUN)) try(eval(parse(text = i)), silent = T)
rm(i)

source("./R/internal_functions.R")
load("~/Dropbox/R_package_testing/suwo/R/sysdata.rda")
source("./R/taxon_code_search.R")

setwd(tempdir())
df1 <- query_macaulay(term = 'Glaucis', path = tempdir())

df1 <- query_macaulay(term = 'Glaucis dohrnii', path = tempdir())
df1 <- query_macaulay(term = 'Turdus grayi', path = tempdir())
df1 <- query_macaulay(term = 'Serinus serinus', path = tempdir())

df1 <- query_macaulay(term = 'Chupacabras', path = tempdir())
df1 <- query_macaulay(term = 'Chupacabras', path = tempdir())

# test a query with more than 10000 results
df1 <- query_macaulay(term = 'Calypte costae', format = "image", path = tempdir(), dates = c(1976, 2020, 2022, 2024, 2025, 2026))
 
# usa esta funcion internamente para sacar los rangos
.date_ranges(x = c(1976, 2020, 2022, 2024, 2025, 2026))

.date_ranges(x = seq(2020, 2026, length.out = 6))

```

```{r query_inaturalist, eval = FALSE}

FUN <- "query_inaturalist"

#run function
source(file.path("./R", paste0(FUN,".R")))
# setwd(tempdir())

#open in rstudio
##open.fun(fun = FUN)

# remove objects but no functions
rm(list = setdiff(ls(), c(lsf.str(), "FUN")))

# to troubleshoot internally
for(i in run.def.args(FUN)) try(eval(parse(text = i)), silent = T)
rm(i)

source("./R/internal_functions.R")
load("~/Dropbox/R_package_testing/suwo/R/sysdata.rda")
source("./R/taxon_code_search.R")

setwd(tempdir())

df1 <- query_inaturalist(term = 'Glaucis dohrnii')
df1 <- query_inaturalist(term = 'Turdus grayi')
df1 <- query_inaturalist(term = 'Serinus serinus')

df1 <- query_macaulay(term = 'Chupacabras')
df1 <- query_macaulay(term = 'Chupacabras')


```


```{r map_locations}

FUN <- "map_locations"

#run function
source(file.path("./R", paste0(FUN,".R")))
# setwd(tempdir())

# remove objects but no functions
rm(list = setdiff(ls(), c(lsf.str(), "FUN")))

# to troubleshoot internally
for(i in run.def.args(FUN)) try(eval(parse(text = i)), silent = T)
rm(i)

source("./R/internal_functions.R")


# search in xeno-canto
metadata_xc <- query_xenocanto(term = "Phaethornis ruber")

# create map
map_locations(metadata = metadata_xc)

metadata_xc2 <- query_xenocanto(term = "Phaethornis anthophilus")

# create map
map_locations(metadata = metadata_xc2)

metadata_ob <- query_gbif(term = "Phaethornis ruber", format = "sound")

 # create map
map_locations(metadata_ob)


```

```{r}

taxon_code_df <- read.csv("./examples/Clements-v2024-October-2024-rev.csv", na.strings = "")

usethis::use_data(taxon_code_df, internal = TRUE, overwrite = TRUE)

```


# Homogenize column names across repos
```{r, eval = FALSE}
# all data false

options(all_data = FALSE, verbose = TRUE)

xc_adf <- query_xenocanto(term = 'Glaucis dohrnii')

wa_adf <- query_wikiaves(term = 'Glaucis dohrnii', format = "sound")
 
gb_adf <- query_gbif(term = 'Glaucis dohrnii', format = "sound")

in_adf <- query_inaturalist(term = 'Glaucis dohrnii', format = "image")
 
ml_adf <- query_macaulay(term = 'Glaucis dohrnii', format = "sound", path = tempdir())


adf_list <- list(xc_adf[1:2, ], wa_adf[1:2, ], gb_adf[1:2, ], in_adf[1:2, ], ml_adf[1:2, ])

sapply(adf_list, ncol)

nms <- lapply(adf_list, names)
names(nms) <- c("xc", "wa", "gb", "in", "ml")
nms

# all functions return the same columns
all(table(unlist(nms)) == 5)

sapply(adf_list, names)

adf_list_full <- list(xc_adf, wa_adf, gb_adf, in_adf, ml_adf)

all_adf <- do.call(rbind, adf_list_full)

all_adf$time

# all data true

options(all_data = TRUE)

xc_adt <- query_xenocanto(term = 'Phaethornis anthophilus')

wa_adt <- query_wikiaves(term = 'Glaucis dohrnii', format = "sound")
 
gb_adt <- query_gbif(term = 'Glaucis dohrnii', format = "image")

in_adt <- query_inaturalist(term = 'Agalychnis lemur', format = "image")
 
ml_adt <- query_macaulay(term = 'Glaucis dohrnii', format = "sound", path = tempdir())

adt_list <- list(xc_adt[1:2, ], wa_adt[1:2, ], gb_adt[1:2, ], in_adt[1:2, ], ml_adt[1:2, ])

names(adt_list) <- c("xc", "wa", "gb", "in", "ml")

sapply(adt_list, ncol)

nms <- lapply(adt_list, names)
names(nms) <- c("xc", "wa", "gb", "in", "ml")
nms

tbnms <- table(unlist(nms))



sort(tbnms)

un_nms <- unique(unlist(nms))

sort(un_nms)

basic_colms <- unique(lapply(adf_list, names))[[1]]

# do all have basic columns
all(sapply(nms, function(x) length(basic_colms[!basic_colms %in% x])) == 0)

nms_by_fun <- do.call(rbind, lapply(seq_along(adt_list), function(x) data.frame(fun = names(adt_list)[x], col = names(adt_list[[x]]))))

nms_by_fun <- nms_by_fun[!nms_by_fun$col %in% (basic_colms),]

nms_by_fun[order(nms_by_fun$col), ]


xc_adt$recordist
wa_adt$author
gb_adt$recordist
unique(in_adt$attribution)

# get everything before the comma
strsplit(unique(in_adt$attribution), ",")[[1]][1]

in_adt$recordist <- sapply(strsplit(in_adt$attribution, ","), "[[", 1)

in_adt$recordist <- sapply(strsplit(in_adt$recordist, ") "), "[[", 2)

ml_adt$recordist

```

# get observation token
```{r}

curl -X POST https://observation.org/api/v1/oauth2/token/ \
-d "client_id=<maRce10>&grant_type=password&email=<marcelo.araya@ucr.ac.cr>&password=<chichi3000X>"


curl -X POST https://observation.org/api/v1/oauth2/token/ \
-d "client_id=1161266&grant_type=password&email=maRce10&password=chichi5000X"


# curl -X POST https://observation.org/api/v1/oauth2/token/ -d  "client_id=1161267&grant_type=password&email=marceloa27@gmail.com&password=chichi3000X"

curl -X POST https://observation.org/api/v1/oauth2/token/ \ -d "client_id='1161266'&grant_type='client_credentials'&email='marcelo.araya@ucr.ac.cr'&password='chichi3000X'"

curl -X POST https://observation.org/api/v1/oauth2/token/ 
-d "client_id=<client_id>&grant_type=password&email=<email>&password=<passsword>"


curl -X POST https://observation.org/api/v1/user/register/ -d "name=Marcelo&email=marcelo.araya@ucr.ac.cr&password=chichi3000X&is_mail_allowed=true&country=CR"

curl -X POST https://observation.org/api/v1/user/register/ -d "name=Marcelo&email=marceloa27@gmail.com&password=chichi3000X&is_mail_allowed=true&country=CR"
```

